Repository bcgov/jag-mail-it, pull requests merged in 2021-03, with the labels that each got.

#4 FIRST!
  src/jag-mail-it/.gitignore
  src/jag-mail-it/pom.xml
  src/jag-mail-it/src/main/java/ca/bc/gov/open/jag/jagmailit/JagMailItApplication.java
  src/jag-mail-it/src/main/resources/application.yml
  src/jag-mail-it/src/test/java/ca/bc/gov/open/jag/jagmailit/JagMailItApplicationTests.java
Labels: bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, wontfix

#12 Adding intial email config
  src/jag-mail-it/pom.xml
  src/jag-mail-it/src/main/resources/application.yml
Labels: Hello, It's Working, porkchopsandwiches

#16 complete implementation of sendmail
  src/jag-mail-it/pom.xml
  src/jag-mail-it/src/main/java/ca/bc/gov/open/jag/jagmailit/mail/MailApiDelegateImpl.java
  src/jag-mail-it/src/main/java/ca/bc/gov/open/jag/jagmailit/mail/mappers/SimpleMessageMapper.java
  src/jag-mail-it/src/main/resources/application.yml
  src/jag-mail-it/src/test/java/ca/bc/gov/open/jag/jagmailit/mail/MailApiDelegateImplTest.java
Labels: Hello
